// =============================================
// Smart Contract Deployment Script
// =============================================
// Deploys the EMRHashRegistry contract to Ganache.
// Run this AFTER starting Ganache.
//
// Usage: node deploy.js
// =============================================

const { ethers } = require('ethers');
require('dotenv').config({ path: '../backend/.env' });

// Minimal compiled ABI and bytecode for EMRHashRegistry
// In production you'd compile with solc, but for this prototype
// we embed the compiled output directly.
const CONTRACT_ABI = [
    "constructor()",
    "function storeHash(string memory recordId, string memory hash) public",
    "function getHash(string memory recordId) public view returns (string memory)",
    "function hasHash(string memory recordId) public view returns (bool)",
    "function verifyHash(string memory recordId, string memory hash) public returns (bool)",
    "function getRecordInfo(string memory recordId) public view returns (string memory hash, bool exists)",
    "function owner() public view returns (address)",
    "event HashStored(string indexed recordId, string hash, uint256 timestamp, address storedBy)",
    "event HashVerified(string indexed recordId, bool isValid, uint256 timestamp)"
];

// This bytecode is generated by compiling EMRHashRegistry.sol
// We'll generate it using solc. For now, provide instructions.
async function main() {
    console.log('=============================================');
    console.log('  EMRHashRegistry — Deployment Script');
    console.log('=============================================\n');

    const rpcUrl = process.env.GANACHE_RPC_URL || 'http://127.0.0.1:7545';
    const privateKey = process.env.GANACHE_PRIVATE_KEY;

    if (!privateKey || privateKey.includes('your_')) {
        console.error('❌ GANACHE_PRIVATE_KEY not set in backend/.env');
        console.log('\nTo get your private key:');
        console.log('1. Open Ganache');
        console.log('2. Click the 🔑 key icon next to any account');
        console.log('3. Copy the private key');
        console.log('4. Paste it in backend/.env as GANACHE_PRIVATE_KEY\n');
        process.exit(1);
    }

    try {
        console.log(`Connecting to Ganache at ${rpcUrl}...`);
        const provider = new ethers.JsonRpcProvider(rpcUrl);
        const wallet = new ethers.Wallet(privateKey, provider);
        const balance = await provider.getBalance(wallet.address);

        console.log(`✅ Connected! Deployer: ${wallet.address}`);
        console.log(`   Balance: ${ethers.formatEther(balance)} ETH\n`);

        console.log('Deploying EMRHashRegistry...');

        // NOTE: To actually deploy, we need compiled bytecode.
        // Install solc and compile, or use the pre-compiled bytecode.
        // For the prototype, we'll check if solc is available.

        let bytecode;
        const solc = require('solc');
        const fs = require('fs');
        const source = fs.readFileSync(__dirname + '/EMRHashRegistry.sol', 'utf8');

        const input = {
            language: 'Solidity',
            sources: { 'EMRHashRegistry.sol': { content: source } },
            settings: {
                evmVersion: 'paris',
                outputSelection: { '*': { '*': ['abi', 'evm.bytecode'] } }
            }
        };

        const output = JSON.parse(solc.compile(JSON.stringify(input)));

        if (output.errors) {
            const errors = output.errors.filter(e => e.severity === 'error');
            if (errors.length > 0) {
                console.error('Compilation errors:');
                errors.forEach(e => console.error(e.formattedMessage));
                process.exit(1);
            }
        }

        const contract = output.contracts['EMRHashRegistry.sol']['EMRHashRegistry'];
        bytecode = contract.evm.bytecode.object;
        const abi = contract.abi;
        console.log('✅ Contract compiled successfully');

        const factory = new ethers.ContractFactory(abi, '0x' + bytecode, wallet);
        const contractInstance = await factory.deploy();
        await contractInstance.waitForDeployment();

        const contractAddress = await contractInstance.getAddress();

        console.log('\n✅ =============================================');
        console.log(`✅ CONTRACT DEPLOYED SUCCESSFULLY!`);
        console.log(`✅ Address: ${contractAddress}`);
        console.log('✅ =============================================\n');
        console.log('📋 Next steps:');
        console.log(`   1. Copy this address: ${contractAddress}`);
        console.log('   2. Paste it in backend/.env as CONTRACT_ADDRESS');
        console.log('   3. Restart the backend server\n');

    } catch (error) {
        console.error('❌ Deployment failed:', error.message);
        if (error.message.includes('ECONNREFUSED')) {
            console.log('\n💡 Make sure Ganache is running!');
            console.log('   Start Ganache and try again.\n');
        }
    }
}

main();
